name: wasiapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  firebase_ml_model_downloader: ^0.3.0
  image_picker: ^1.1.1
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  image: ^4.1.7
  cloud_firestore: ^5.6.12
  tflite_flutter: ^0.12.1
  printing: ^5.11.2
  pdf: ^3.10.4
  open_file: ^3.3.3
  path_provider: ^2.1.1
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt  # â† SOLO las etiquetas
