name: wasiapp
description: "WassiApp - Aplicación para detección de anemia infantil"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_ml_model_downloader: ^0.3.2+1
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.20.1
  shared_preferences: ^2.3.4
  image: ^4.3.0
  cloud_firestore: ^5.6.0
  tflite_flutter: ^0.12.1
  printing: ^5.13.5
  pdf: ^3.11.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_lints: ^6.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt  # ← SOLO las etiquetas
    - assets/logo.png    # ← Logo de la aplicación

# Configuración del ícono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # ← Coloca aquí tu logo
  adaptive_icon_background: "#FFFFFF"  # Color de fondo (blanco)
  adaptive_icon_foreground: "assets/logo.png"  # Logo para Android adaptivo
